### PR TITLE
Fix display of widget when there are no articles.

### PR DESCRIPTION
**Pull request by kwisatz**
When there are no articles, the ending list, list-element and div tags were still being printed, causing the site layout to break.

The elements must be inside the 
```php
if ($results) {
}
```
conditional, not outside it.

### CODE REVIEW

**Comment by mpetroff** [comment]
The fix looks good, but please don't change the version number (particularly not to something that doesn't match the existing versioning scheme).

**Comment by kwisatz** [comment]
My apologies, I thought you were observing `semver`. Update coming right up.

**Comment by mpetroff** [comment]
Thanks!

**Comment by mpetroff** [comment]
I just pushed this fix to the plugins directory in version 1.4.

**Pull request merged**
